import { useEffect,useMemo,useState } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { CartesianGrid,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { api,type SecurityActivity,type SecurityDetailData,type SecurityPositionAction,type SecurityPositionChange } from "../api/client";
const money=(v:number|string|null)=>{if(v==null)return"—";const n=Number(v);return n>=1e9?`$${(n/1e9).toFixed(1)}B`:n>=1e6?`$${(n/1e6).toFixed(1)}M`:`$${Math.round(n).toLocaleString()}`};
const pct=(v:number|string|null)=>v==null?"—":`${Number(v)>=0?"+":""}${(Number(v)*100).toFixed(1)}%`;
const count=(v:number|string)=>Math.abs(Number(v)).toLocaleString();
function Activity({title,rows}:{title:string;rows:SecurityActivity[]}){const nav=useNavigate();return <section className="attribution-panel"><h3>{title}</h3><table><thead><tr><th>Fund</th><th>Action</th><th className="text-right">Δ Shares</th><th className="text-right">Value</th></tr></thead><tbody>{rows.map(r=><tr className="clickable-row" key={r.fund_id} onClick={()=>nav(`/funds/${r.fund_id}`)}><td>{r.name}</td><td><span className={`change-pill change-${r.action==='add'?'added':r.action}`}>{r.action}</span></td><td className={`text-right ${Number(r.shares)-Number(r.previous_shares)>=0?'positive':'negative'}`}>{count(Number(r.shares)-Number(r.previous_shares))}</td><td className="text-right">{money(r.action==='exit'?r.previous_value:r.value_usd)}</td></tr>)}</tbody></table></section>}
const positionMarkers:Record<SecurityPositionAction,{icon:string;label:string}>={
 new:{icon:"★",label:"New position"},add:{icon:"▲",label:"Added"},reduce:{icon:"▼",label:"Reduced"},exit:{icon:"×",label:"Exited"},unchanged:{icon:"—",label:"Unchanged"}
};
function PositionChanges({quarters,rows}:{quarters:string[];rows:SecurityPositionChange[]}){
 const funds=[...new Map(rows.map(row=>[row.fund_id,{fund_id:row.fund_id,name:row.name,fund_type:row.fund_type}])).values()];
 const cells=new Map(rows.map(row=>[`${row.fund_id}:${row.report_period}`,row]));
 return <section className="card"><h2>Position Change</h2><p className="chart-note">Each quarter compares a fund's reported shares with its preceding available 13F filing.</p>
  <div className="position-change-legend">{(["new","add","reduce","exit"] as SecurityPositionAction[]).map(action=><span key={action}><i className={`position-marker position-${action}`}>{positionMarkers[action].icon}</i>{positionMarkers[action].label}</span>)}</div>
  <div className="table-scroll"><table className="position-change-table"><thead><tr><th>Fund</th>{quarters.map(quarter=><th className="text-center" key={quarter}>{quarter}</th>)}</tr></thead><tbody>
   {funds.map(fund=><tr key={fund.fund_id}><td><Link to={`/funds/${fund.fund_id}`}><strong>{fund.name}</strong></Link><small>{fund.fund_type}</small></td>{quarters.map(quarter=>{const cell=cells.get(`${fund.fund_id}:${quarter}`);if(!cell)return <td className="text-center position-empty" key={quarter}>·</td>;const marker=positionMarkers[cell.action];const title=`${marker.label}: ${Number(cell.previous_shares).toLocaleString()} → ${Number(cell.shares).toLocaleString()} shares`;return <td className="text-center" key={quarter}><span className={`position-marker position-${cell.action}`} title={title} aria-label={title}>{marker.icon}</span></td>})}</tr>)}
  </tbody></table></div>
 </section>
}
export default function SecurityDetail(){const ticker=String(useParams().ticker||"").toUpperCase();const nav=useNavigate();const [data,setData]=useState<SecurityDetailData|null>(null);const [error,setError]=useState("");
 useEffect(()=>{api.security(ticker).then(setData).catch(e=>setError(e.message))},[ticker]);
 const chart=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.prices.forEach(p=>m.set(p.price_date,{date:p.price_date,price:Number(p.price)}));data.history.forEach(h=>m.set(h.report_period,{...(m.get(h.report_period)||{date:h.report_period}),shares:Number(h.aggregate_shares),funds:h.fund_count}));return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date))},[data]);
 if(error)return <div className="error">{error}</div>;if(!data)return <div className="loading">Loading security...</div>;const s=data.security;const total=data.owners.reduce((a,r)=>a+Number(r.value_usd),0);
 return <><Link to="/securities" className="back-link">&larr; Back to Securities</Link><div className="page-header"><h1>{s.ticker} <span className="security-company">{s.company}</span></h1><p>Latest price {s.latest_price==null?'—':`$${Number(s.latest_price).toFixed(2)}`} · {s.price_date} · First tracked {s.first_appearance}</p></div>
 <div className="security-stats"><div className="quarter-return-card"><div className="quarter-label">Current tracked owners</div><div className="quarter-value">{data.owners.length}</div></div><div className="quarter-return-card"><div className="quarter-label">Aggregate 13F value</div><div className="quarter-value">{money(total)}</div></div><div className="quarter-return-card"><div className="quarter-label">Latest-quarter buyers</div><div className="quarter-value positive">{data.buyers.length}</div></div><div className="quarter-return-card"><div className="quarter-label">Latest-quarter sellers</div><div className="quarter-value negative">{data.sellers.length}</div></div></div>
 <section className="card"><h2>Price and Aggregate 13F Ownership</h2><p className="chart-note">The green step line is the aggregate shares reported by tracked funds for each quarter. A quarter with no reported holding is zero.</p><div className="price-chart"><ResponsiveContainer><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#2e3344"/><XAxis dataKey="date" stroke="#9aa0b0" fontSize={11}/><YAxis yAxisId="price" stroke="#4f8cff"/><YAxis yAxisId="shares" orientation="right" stroke="#10b981" tickFormatter={v=>Number(v).toLocaleString("en-US",{notation:"compact"})}/><Tooltip contentStyle={{background:'#222633',border:'1px solid #2e3344'}} formatter={(value,name)=>name==='Quarter-end shares'?[Number(value).toLocaleString('en-US'),name]:[`$${Number(value).toFixed(2)}`,name]}/><Line connectNulls yAxisId="price" dataKey="price" name="Price" stroke="#4f8cff" dot={false}/><Line connectNulls yAxisId="shares" type="stepAfter" dataKey="shares" name="Quarter-end shares" stroke="#10b981" strokeWidth={2} dot/></ComposedChart></ResponsiveContainer></div></section>
 <section className="card"><h2>Latest Quarter Activity</h2><div className="attribution-grid"><Activity title="New / Added" rows={data.buyers}/><Activity title="Reduced / Exited" rows={data.sellers}/></div></section>
 <section className="card"><h2>Current Owners</h2><div className="table-scroll"><table><thead><tr><th>Fund</th><th>Type</th><th className="text-right">Value</th><th className="text-right">Shares</th><th className="text-right">Fund Weight</th><th>First Owned</th></tr></thead><tbody>{data.owners.map(r=><tr className="clickable-row" key={r.fund_id} onClick={()=>nav(`/funds/${r.fund_id}`)}><td><strong>{r.name}</strong></td><td>{r.fund_type}</td><td className="text-right">{money(r.value_usd)}</td><td className="text-right">{count(r.shares)}</td><td className="text-right">{pct(r.portfolio_weight)}</td><td>{r.first_owned}</td></tr>)}</tbody></table></div></section>
 <PositionChanges quarters={data.position_changes.quarters} rows={data.position_changes.rows}/>
 </>}
